### ISSUE TITLE
https://meteorlxy.cn/ 的问题

### ISSUE THREAD

**Issue by xjtushilei** [meteorlxy/meteorlxy.github.io#1]
https://meteorlxy.cn/  为什么是个phpmyadmin，还有就是https证书配置有问题呀

**Comment by meteorlxy** [comment]
噗，居然被你找到我了……主要是我首页一直没配置，这个地址目测是被我重定向到其他地方了

**Comment by xjtushilei** [comment]
哈哈 怎么感觉你是做前端的。还是前端安全？ 还是什么？

**Comment by meteorlxy** [comment]
实习投的都是前端开发岗
