### ISSUE TITLE
[Comments] 2018年互联网公司暑期实习笔试面试经历

### ISSUE THREAD

**Issue by meteorlxy** [meteorlxy/meteorlxy.github.io#19]
http://localhost:8080/posts/2018/06/06/internship-of-2018.html

**Comment by caohenghu** [comment]
找vuepress主题看到你这个了，还挺不错的。看了你的面经，正好回答文中的一个问题。监听搜索框的keyup事件，粘贴动作不一定会触发。因为粘贴不一定就是ctrl+v，也有可能是鼠标右键粘贴。而且还有其它的情况要考虑，比如鼠标拖入文字、中文输入法等等。
